services:
  # Zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: oms-zookeeper
    ports:
      - "2180:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  # Kafka 
  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: oms-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
    networks:
      - oms_ims_network
    restart: always

  # MongoDB
  mongodb:
    image: mongo:6
    container_name: oms-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: oms

  # Redis
  redis:
    image: redis:7-alpine
    container_name: oms-redis
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data
    networks:
      - oms_ims_network
    restart: always

  # LocalStack
  localstack:
    image: localstack/localstack
    container_name: oms-localstack
    ports:
      - "4566:4566" 
    environment:
      - SERVICES=s3,sqs,sns,dynamodb
      - DEBUG=1
    volumes:
      - "./localstack:/var/lib/localstack"

volumes:
  mongodb_data:
  redis_data:


networks:
  oms_ims_network:
    driver: bridge
